## roles/ansible-role-sudo/tasks/main.yml
# vim:ft=yaml.ansible:
---
- name: "Install libselinux-python"
  package:
    name: libselinux-python
    state: present
  when: "'Fedora' in ansible_distribution"
  tags: sudo,selinux

- name: "Install libselinux-python"
  package:
    name: python3-libselinux
    state: present
  when: "'RedHat' in ansible_distribution"
  tags: sudo,selinux

- name: "Install sudo"
  package:
    name: sudo
    state: present
  tags: sudo

- name: "Config sudoers"
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
  tags: sudo
...
