## roles/ansible-role-sudo/tasks/main.yml
# vim:ft=ansible:
---
- name: "Install sudo"
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - "sudo"
    - "libselinux-python"
  tags: sudo

- name: "Config sudoers"
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
  tags: sudo
...
